{"uuid":"91ce7365-aa75-4c23-a9ad-54f6f03a1e6b","historyId":"c59643030e1e776644fd5d1d6aa79cfc","status":"failed","statusDetails":{"message":"The following error originated from your test code, not from Cypress.\n\n  > Cannot call `cy.type()` outside a running test.\n\nThis usually happens when you accidentally write commands outside an `it(...)` test.\n\nIf that is the case, just move these commands inside an `it(...)` test.\n\nCheck your test file for errors.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.","trace":"CypressError: The following error originated from your test code, not from Cypress.\n\n  > Cannot call `cy.type()` outside a running test.\n\nThis usually happens when you accidentally write commands outside an `it(...)` test.\n\nIf that is the case, just move these commands inside an `it(...)` test.\n\nCheck your test file for errors.\n\nWhen Cypress detects uncaught errors originating from your test code it will automatically fail the current test.\n\nCypress could not associate this error to any specific test.\n\nWe dynamically generated a new test to display this failure.\n    at $Cy.ensureRunnable (http://localhost:55324/__cypress/runner/cypress_runner.js:147775:76)\n    at cy.<computed> [as type] (http://localhost:55324/__cypress/runner/cypress_runner.js:157896:10)\n    at <unknown> (http://localhost:55324/__cypress/runner/cypress_runner.js:165963:23)\nFrom previous event:\n    at evalScripts (http://localhost:55324/__cypress/runner/cypress_runner.js:165956:58)\n    at <unknown> (http://localhost:55324/__cypress/runner/cypress_runner.js:165968:152)\nFrom previous event:\n    at runScriptsFromUrls (http://localhost:55324/__cypress/runner/cypress_runner.js:165968:136)\n    at Object.runScripts (http://localhost:55324/__cypress/runner/cypress_runner.js:165983:12)\n    at $Cypress.onSpecWindow (http://localhost:55324/__cypress/runner/cypress_runner.js:153939:75)"},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1669886808486,"name":"task (\"log\"; \"I run before every test in every spec file*******\")","stop":1669886808490}],"attachments":[],"parameters":[],"start":1669886808485,"name":"log (\"I run before every test in every spec file*******\")","stop":1669886808490}],"attachments":[],"parameters":[],"start":1669886808485,"name":"\"before each\" hook","stop":1669886808491},{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1669886808493,"name":"task (\"log\"; \"I run after each every test in every spec file-------\")","stop":1669886808495}],"attachments":[],"parameters":[],"start":1669886808493,"name":"log (\"I run after each every test in every spec file-------\")","stop":1669886808495}],"attachments":[],"parameters":[],"start":1669886808492,"name":"\"after each\" hook","stop":1669886808495}],"attachments":[{"name":"testUtilityFirstPage.spec.js.mp4","type":"video/mp4","source":"/Users/achantaprakash/Projects/Native Base/nativebase-docs/test-automation-cypress/cypress/videos/testUtilityFirstPage.spec.js.mp4"}],"parameters":[],"labels":[],"links":[],"start":1669886808470,"name":"An uncaught error was detected outside of a test","fullName":"An uncaught error was detected outside of a test","stop":1669886808492}